{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tailscale-subnet-router-secrets",
    "namespace": "tailscale"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tailscale-subnet-router-secrets",
        "namespace": "tailscale"
      }
    },
    "encryptedData": {
      "AUTH_KEY": "AgA9OuygUZCVh1KJP4jHAg/q4sbDibJOdpJIbKPK74OHPoqOQFxLrQGRNAZSfFM0wX7TVzSMTUK6mkpPLRV5wmH481QpyMssS3ejukMH1nUVkdyD5xZ+23YGPsZAnzEskESh1NYqhn80dumZYajDxMq+NbU1XawjiIvpnauTGP7I4rsuS2KX/KkF4ddmZ7bfio/QOn03Rae9oEnhVK50MX+YbooCeSEK6XQUOUSAIZYzvCEM/IgBoSUy7ZS4TLsKKsDG9C+1bkrLy5SlljoEfOlIMdlv2E63VakELVXeJQ0x09TzS82p1tIGbtB9FwDUw3pDxcwLDsHUQtBMZH+NgQK/e3lIjY+LmSULYNnLdJjiP0phdOV13Vzr3ryKaykBWbfr8P4XveCE80LjQAwnuZnFpMj4+KSz0Ww2Jo2nfVKxNIdFONgWif+jzrCG5Y5AZqCOJiL2L3ZZh9eIHUhbSSboBcObGlkqMXREoC0ZGRnLLKr/9ArzEPRFSc4n+TCjoE8jkOQQnzQ1DeE0uuZ19HPYdcBevHW5NPtupD561WWDaf30MG4oNhHYBoWQNMKbU6rmanSlVJ9Y/qpWTUQhUzKUDyOvL0zI0LttXNP8bczW8Qe/Q8WEd3ThlgyL0MjHZb18p/ND7fycmjko1MI9PCiAU4nyPQXhLzTwrkQd4MncjPv0V3XwJSO6EZXoiemQU7tqivwhfHRq4dCCKruwVUr3FvcyyQpmqXT7Vx0EUWbPohgeXeIFXu1FAYwIcD9dWxqzS7CV+hGVRXXn5BRxLg=="
    }
  }
}
