apiVersion: batch/v1
kind: Job
metadata:
  name: couchdb-post-install
  namespace: obsidian-sync
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: couchdb-post-install
      name: couchdb-post-install
    spec:
      containers:
        - command:
            - sh
            - -c
            - 'curl -s http://$COUCHDB_ADDRESS/_cluster_setup -X POST -H "Content-Type:
              application/json" -d "{\"action\": \"finish_cluster\"}" -u $COUCHDB_ADMIN:$COUCHDB_PASS
              && export IFS=","; for db_name in $DEFAULT_DBS; do curl -X PUT http://$COUCHDB_ADDRESS/$db_name
              -u $COUCHDB_ADMIN:$COUCHDB_PASS; done'
          env:
            - name: DEFAULT_DBS
              value: _global_changes,_users,obsidian
            - name: COUCHDB_ADDRESS
              value: couchdb-svc-couchdb.obsidian-sync.svc.cluster.local:5984
            - name: COUCHDB_ADMIN
              valueFrom:
                secretKeyRef:
                  key: adminUsername
                  name: couchdb-admin
            - name: COUCHDB_PASS
              valueFrom:
                secretKeyRef:
                  key: adminPassword
                  name: couchdb-admin
          image: curlimages/curl:latest
          imagePullPolicy: Always
          name: cluster-setup
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 600
