apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian-sync

resources:
  - namespace.yaml

helmCharts:
  - name: couchdb
    releaseName: couchdb
    namespace: obsidian-sync
    version: 4.6.3
    repo: https://apache.github.io/couchdb-helm
    valuesFile: values.yaml
